heat_template_version: 2014-10-16
description: none

parameter_groups:

parameters:
  public_network_external:
    description: Public Internet Floating Address
    type: string
    constraints:
      - custom_constraint: neutron.network
    default: float_internet

resources:

  internal_net:
    description: Internal Network
    type: OS::Neutron::Net
    properties:
      name: internal_network

  internal_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: internal_subnet
      network_id: { get_resource: internal_net }
      cidr: 192.168.1.0/24
      dns_nameservers:
        - 192.168.1.1

  external_router:
    type: OS::Neutron::Router
    properties:
      name: external-router
      external_gateway_info:
        network: { get_param: public_network_external }

  external_network_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id:  { get_resource: external_router }
      subnet: { get_resource: internal_subnet }

outputs:

  external_router:
    value: { get_resource: external_router }

  internal_router:
    value: { get_resource: internal_router }
