heat_template_version: 2015-04-30
description: none
resources:
  nginx_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: nginx_security_group
      rules:

	# port 22
        - protocol: tcp
          ethertype: IPv4
          port_range_min: 22
          port_range_max: 2
          remote_ip_prefix:  0.0.0.0/0
          direction: ingress

	# port 80
        - protocol: tcp
          ethertype: IPv4
          port_range_min: 80
          port_range_max: 80
          remote_ip_prefix:  0.0.0.0/0
          direction: ingress

	# port 443
        - protocol: tcp
          ethertype: IPv4
          port_range_min: 443
          port_range_max: 443
          remote_ip_prefix:  0.0.0.0/0
          direction: ingress

	# icmp
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
          direction: egress

	# outgoing
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          direction: egress
        - protocol: udp
          remote_ip_prefix: 0.0.0.0/0
          direction: egress

  app_servers_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: app_servers_security_group
      rules:

	# icmp
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
          direction: egress

	# tcp
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          direction: egress
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress

	# udp
        - protocol: udp
          remote_ip_prefix: 0.0.0.0/0
          direction: egress
        - protocol: udp
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress


  db_servers_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: db_servers_security_group
      rules:

	# icmp
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
          direction: egress

	# tcp
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          direction: egress
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress

	# udp
        - protocol: udp
          remote_ip_prefix: 0.0.0.0/0
          direction: egress
        - protocol: udp
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
